grails-app/domain/com/ponychan/db/forum/ForumThread.groovy
package com.ponychan.db.forum

class ForumThread extends ForumObject {
    String topic

    static belongsTo = [parent: ForumBoard]
    static hasMany   = [children: ForumPost]
    
    public findObject(ForumObject object) {
        def found = children.find {it == object}
        
        return found
    }
    
    static constraints = {
		topic nullable: true
    }
}

grails-app/controllers/com/ponychan/db/forum/ForumPostController.groovy
package com.ponychan.db.forum

import com.ponychan.db.users.*

class ForumPostController {
	
	def fileService
	def userService

    def index() { }
    
    def save() {
		def user = userService.getCurrentUser()
		session["lastNameUsed"] = [name: params.name, email: params.email]
		
		if (!user) {
			println "Unknown error."
			flash.message = "Unknown error."
			redirect(controller: "forumThread", action: "show", id: params.parent.id)
			return
		}
		
		if (!userService.canPost()) {
			println "You must wait before you can post again."
			flash.message = "You must wait before you can post again."
			redirect(controller: "forumThread", action: "show", id: params.parent.id)
			return
		}
		
		def f = request.getFile('uploadFile')
		def map = fileService.store(f)
		def path = map.path
		def thumb = map.thumb
		
        def post = new ForumPost(params)
		post.owner = user
		post.email = params.email
		
		//Bump
		def parent = ForumThread.get(params.parent.id)
		if (parent) {
			parent.lastUpdated = new Date()
			parent.save()
		}
		
		if (path) {
			post.attachedImage = path
			post.attachedThumbnail = thumb
	        post.hasAttachedImage = true
		}
		
		user.addToForumObjects(post)
		user.lastPost = user.lastSeen = new Date()
		
        if (!post.save(flush: true)) {
            flash.message = post.errors
            redirect(controller: "forumThread", action: "show", id: params.parent.id)
            return
        }
		
		if (!user.save(flush: true)) {
			flash.message = user.errors
			redirect(controller: "forumThread", action: "show", id: params.parent.id)
			return
		}
		
		println "POSTER NAME: ${post.name}"
		println "EMAIL:       ${post.email}"
        
        redirect(controller: "forumThread", action: "show", id: params.parent.id, params: [board: post.parent.parent.abbreviation.replaceAll("/", "")])
    }
}

grails-app/controllers/com/ponychan/db/forum/ForumThreadController.groovy
package com.ponychan.db.forum

import com.ponychan.db.users.*

class ForumThreadController {
	
	def fileService
	def userService

    def index() { }
    
    def show(Long id) {
        def thread = ForumThread.get(id)
		
		def lastNameUsed = session["lastNameUsed"]
        
        if (!thread) {
            println "No thread with id ${id}"
            response.status = 404
			return
        }
        
        [thread: thread, last: lastNameUsed]
    }
    
    def save() {
		def user = userService.getCurrentUser()
		
		session["lastNameUsed"] = [name: params.name, email: params.email]
		
		if (!user) {
			println "Unknown error."
			flash.message = "Unknown error."
			redirect(controller: "forumBoard", action: "show", id: params.parent.id)
			return
		}
		
		if (!userService.canPost()) {
			println "You must wait before you can post again."
			flash.message = "You must wait before you can post again."
			redirect(controller: "forumBoard", action: "show", id: params.parent.id)
			return
		}
		
		//Get file
		def f = request.getFile('uploadFile')
		def map = fileService.store(f)
		def path = map.path
		def thumb = map.thumb
		
		if (!path) {
			println "You must attach a picture to start a thread!"
			flash.message = "You must attach a picture to start a thread!"
			redirect(controller: "forumBoard", action: "show", id: params.parent.id)
			return
		}
		
        def thread = new ForumThread(params)
        def firstPost = new ForumPost()
		
		firstPost.name = params.name
		firstPost.topic = params.topic
        firstPost.text = params.post.text
		firstPost.email = params.email
		firstPost.owner = user
		firstPost.attachedImage = path
		firstPost.attachedThumbnail = thumb
		firstPost.hasAttachedImage = true
		
		thread.owner = user
        thread.addToChildren(firstPost)
		
		user.addToForumObjects(thread)
		user.addToForumObjects(firstPost)
		user.lastPost = user.lastSeen = new Date()
        
        if (!thread.save()) {
            println "ERRORS:"
            thread.errors.each {println it}
            flash.message = thread.errors
            redirect(controller: "forumBoard", action: "show", id: params.parent.id)
            return
        }
		
		if (!user.save()) {
			println "ERRORS:"
			user.errors.each {println it}
			flash.message = user.errors
			redirect(controller: "forumBoard", action: "show", id: params.parent.id)
			return
		}
		
		println "POSTER NAME: ${firstPost.name}"
		println "EMAIL:       ${firstPost.email}"
        
        redirect(action: "show", id: thread.id, params: [board: thread.parent.abbreviation.replaceAll("/", "")])
    }
}

grails-app/views/forumThread/_newPostForm.gsp
<div style="border:1px solid black; width:800px">
    <h3>New Post</h3><br/>
    <g:uploadForm controller="forumPost" action="save">
        <label>Email</label><g:textField name="email" /><br/>
        <label>Post</label><g:textArea name="text" /><br/>
        <label>File</label><g:field type="file" name="uploadFile" /><br/>
        <g:hiddenField name="parent.id" value="${thread.id}" /><br/>
        <g:submitButton name="submit" value="Submit" /><br/>
    </g:uploadForm>
</div>

grails-app/views/forumThread/_newThreadForm.gsp
<g:uploadForm controller="forumThread" action="save">
	<table class="new-post">
		<tbody>
			 <tr><td class="label">Name</td><td><g:textField class="new-post" name="name" /></td></tr>
		     <tr><td class="label">Email</td><td><g:textField class="new-post" name="email" /></td></tr>
		     <tr><td class="label">Subject</td><td><g:textField class="new-post" name="topic" /><g:submitButton class="new-post" name="submit" value="Submit" /><br/></td></tr>
		     <tr><td class="label">Post</td><td><g:textArea class="new-post" cols="50" rows="4" name="text" /></td></tr>
		     <tr><td class="label">File</td><td><g:field class="new-post" type="file" name="uploadFile" /></td></tr>
		     <g:hiddenField name="parent.id" value="${board.id}" /><br/>
		</tbody>
    </table>
</g:uploadForm>

grails-app/views/forumThread/_post.gsp
<div class="post-div" style="border:1px solid black; width:800px; minHeight:400px;">
	<g:if test="${post.hasAttachedImage}">
		<div class="post-image-div" style="display:inline-block;">
			<img class="post-image" style="vertical-align: top" src="${createLink(controller: 'file', action: 'getImage', id: post.id)}" width="200px" />
		</div>
	</g:if>
	<div class="post-content" style="display:inline-block;">
	    <div class="post-header" style="vertical-align: top">[${post.dateCreated}]</div>
	    <div class="post-text" style="vertical-align: top">${post.text}</div>
    </div>
</div>

grails-app/views/forumThread/_thread.gsp
<% def first = true %>
<div class="thread">
    <g:each in="${thread.children.sort{it.dateCreated.getTime()}}" var="post">
    	<g:if test="${first}">
    		<% first = false %>
        	<g:render template="/forumPost/post" model="${[post: post, first: true]}"/>
        </g:if>
        <g:else>
        	<g:render template="/forumPost/post" model="${[post: post, first: false]}"/>
        </g:else>
    </g:each>
</div>

grails-app/views/forumThread/_threadPreview.gsp
<% def first = true %>
<div class="thread">
	<%
		def list = thread.children.sort{it.dateCreated.getTime()}
		def preview
	
		if (list.size() >= 4) {
		    preview = list[0..0] + list[-3..-1]
		} else {
		    preview = list
		}
		
		def moreThanThree = list.size() > 3
	%>
    <g:each in="${preview}" var="post">
    	<g:if test="${first}">
    		<% first = false %>
        	<g:render template="/forumPost/post" model="${[post: post, first: true, moreThanThree: moreThanThree, preview: true]}"/>
        </g:if>
        <g:else>
        	<g:render template="/forumPost/post" model="${[post: post, first: false, moreThanThree: moreThanThree, preview: true]}"/>
        </g:else>
    </g:each>
</div>

grails-app/views/forumThread/show.gsp
<html>
	<head>
		<meta name="layout" content="board">
		<title>${thread.topic}</title>
	</head>
	<body>
		<div class="title"><h1 class="board">${thread.parent.abbreviation}- ${thread.parent.name}</h1></div>
		<hr />
		<div class="mode">Posting Mode: Reply</div>
	    <g:render template="/forumPost/newPostForm" model="${[controller: 'forumPost']}" />
	    <hr />
		<g:render template="thread" model="${[thread: thread]}" />
	    <g:link controller="forumBoard" action="board" id="${thread.parent.abbreviation.replaceAll("/", "")}">Return to ${thread.parent.abbreviation}</g:link>
	</body>
</html>