grails-app/domain/com/ponychan/db/forum/ForumBoard.groovy
package com.ponychan.db.forum

import com.sun.xml.internal.ws.org.objectweb.asm.Item;

class ForumBoard extends ForumObject {
    String abbreviation
   
    static belongsTo = [parent: Forum]
    static hasMany   = [children: ForumThread]
    
    public findObject(ForumObject object) {
        def found = children.find {it == object}
        if (!found) {
            for (ForumObject child in children) {
                found = child.findObject(object)
                if (found) {
                    break
                }
            }
            if (!found) {
                return null
            }
        }
        
        return found
    }
    
    public String toString() {
        return "${abbreviation}- ${name} (${id})"
    }

    static constraints = {
    }
}

grails-app/controllers/com/ponychan/db/forum/ForumBoardController.groovy
package com.ponychan.db.forum

//Only the owner of the forum should be able to access this controller
class ForumBoardController {
	def userService
	def paginationService
	
    def show(Long id) {
		params.max = Math.min(params.max ? params.int('max') : 10, 100)
		
        def board = ForumBoard.get(id)
		
		def lastNameUsed = session["lastNameUsed"] 
        
        if (!board) {
            println "Unable to find the requested board"
			flash.message = "Unable to find the requested board"
            redirect(controller: "forum", action: "index")
			return
        }
		
		def map = paginationService.sortAndPaginate(board.children, params)
        
        [board: map.board, threads: map.list, threadCount: map.totalRecords, last: lastNameUsed]
    }
    
    def board(String id) {
		params.max = Math.min(params.max ? params.int('max') : 10, 100)
		
		def board = ForumBoard.findByAbbreviation("/" + id + "/") ?: ForumBoard.findByAbbreviation(id)
		
		def lastNameUsed = session["lastNameUsed"]
        
        println "ABBREV: ${id}"
                
        if (!board) {
            println "Unable to find the requested board"
			flash.message = "Unable to find the requested board"
            redirect(controller: "forum", action: "index")
			return
        }
		
		def map = paginationService.sortAndPaginate(board.children, params)
        
        render(view: "show", model: [board: board, threads: map.list, threadCount: map.totalRecords, last: lastNameUsed])
    }
    
    def create() {
        if (!params.forum) {
            flash.message = "Invalid parameter passed."
            redirect(action: "index")
            return
        }
        
        def forum = Forum.findByName(params.forum)
        
        if (!forum) {
            flash.message = "No forum named ${params.forum}."
            redirect(action: "index")
            return
        }
        
        [forum: forum]
    }
    
    def save() {
        def board = new ForumBoard(params)
        
        if (!board.save(flush:true)) {
            flash.message = board.errors
            redirect(controller: "forum", action: "createBoard")
            return
        }
        
        redirect(controller: "forum", action: "index")
        return
    }
    
    def edit(Long id) {
        def board = ForumBoard.get(id)
        
        if (!board) {
            flash.message = "Cannot find requested board!"
            redirect(controller: "forum", action: "index")
            return
        }
        
        [board: board, forum: board.parent]
    }
	
	def editBoard(String id) {
		def board = ForumBoard.findByAbbreviation("/" + id + "/") ?: ForumBoard.findByAbbreviation(id)
        
        println "ABBREV: ${id}"
                
        if (!board) {
            println "Unable to find the requested board"
			flash.message = "Unable to find the requested board"
            redirect(controller: "forum", action: "index")
			return
        }
		
		render(view: "edit", model: [board: board, forum: board.parent])
	}
    
    def update(Long id) {
        def board = ForumBoard.get(id)
		
		board.properties = params
        
        if (!board.save(flush:true)) {
            flash.message = board.errors
            redirect(controller: "forum", action: "createBoard")
            return
        }
        
        redirect(action: "show")
        return
    }
}

grails-app/controllers/com/ponychan/db/forum/ForumThreadController.groovy
package com.ponychan.db.forum

import com.ponychan.db.users.*

class ForumThreadController {
	
	def fileService
	def userService

    def index() { }
    
    def show(Long id) {
        def thread = ForumThread.get(id)
		
		def lastNameUsed = session["lastNameUsed"]
        
        if (!thread) {
            println "No thread with id ${id}"
            response.status = 404
			return
        }
        
        [thread: thread, last: lastNameUsed]
    }
    
    def save() {
		def user = userService.getCurrentUser()
		
		session["lastNameUsed"] = [name: params.name, email: params.email]
		
		if (!user) {
			println "Unknown error."
			flash.message = "Unknown error."
			redirect(controller: "forumBoard", action: "show", id: params.parent.id)
			return
		}
		
		if (!userService.canPost()) {
			println "You must wait before you can post again."
			flash.message = "You must wait before you can post again."
			redirect(controller: "forumBoard", action: "show", id: params.parent.id)
			return
		}
		
		//Get file
		def f = request.getFile('uploadFile')
		def map = fileService.store(f)
		def path = map.path
		def thumb = map.thumb
		
		if (!path) {
			println "You must attach a picture to start a thread!"
			flash.message = "You must attach a picture to start a thread!"
			redirect(controller: "forumBoard", action: "show", id: params.parent.id)
			return
		}
		
        def thread = new ForumThread(params)
        def firstPost = new ForumPost()
		
		firstPost.name = params.name
		firstPost.topic = params.topic
        firstPost.text = params.post.text
		firstPost.email = params.email
		firstPost.owner = user
		firstPost.attachedImage = path
		firstPost.attachedThumbnail = thumb
		firstPost.hasAttachedImage = true
		
		thread.owner = user
        thread.addToChildren(firstPost)
		
		user.addToForumObjects(thread)
		user.addToForumObjects(firstPost)
		user.lastPost = user.lastSeen = new Date()
        
        if (!thread.save()) {
            println "ERRORS:"
            thread.errors.each {println it}
            flash.message = thread.errors
            redirect(controller: "forumBoard", action: "show", id: params.parent.id)
            return
        }
		
		if (!user.save()) {
			println "ERRORS:"
			user.errors.each {println it}
			flash.message = user.errors
			redirect(controller: "forumBoard", action: "show", id: params.parent.id)
			return
		}
		
		println "POSTER NAME: ${firstPost.name}"
		println "EMAIL:       ${firstPost.email}"
        
        redirect(action: "show", id: thread.id, params: [board: thread.parent.abbreviation.replaceAll("/", "")])
    }
}

grails-app/views/forumBoard/_form.gsp
<label>Name:</label><g:textField name="name" value="${board?.name}" /><br/>
<label>Abbreviation:</label><g:textField name="abbreviation" value="${board?.abbreviation}" />
<g:hiddenField name="parent.id" value="${forum? forum?.id : board?.forum.id}" />

grails-app/views/forumBoard/_newThreadForm.gsp
<div style="border:1px solid black; width:800px">
    <h3>New Thread</h3><br/>
    <g:uploadForm controller="forumThread" action="save">
        <label>Topic</label><g:textField name="topic" /><br/>
        <label>Email</label><g:textField name="email" /><br/>
        <label>Post</label><g:textArea name="post.text" /><br/>
        <label>File</label><g:field type="file" name="uploadFile" /><br/>
        <g:hiddenField name="parent.id" value="${board.id}" /><br/>
        <g:submitButton name="submit" value="Submit" /><br/>
    </g:uploadForm>
</div>

grails-app/views/forumBoard/_post.gsp
<div class="post-div" style="border:1px solid black; width:800px; minHeight:400px;">
	<g:if test="${post.hasAttachedImage}">
		<div class="post-image-div" style="display:inline-block;">
			<img class="post-image" style="vertical-align: top" src="${createLink(controller: 'file', action: 'getImage', id: post.id)}" width="200px" />
		</div>
	</g:if>
	<div class="post-content" style="display:inline-block;">
	    <div class="post-header" style="vertical-align: top">[${post.dateCreated}]</div>
	    <div class="post-text" style="vertical-align: top">${post.text}</div>
    </div>
</div>

grails-app/views/forumBoard/_thread.gsp
<div class="thread-div" style="border:1px solid black; width:800px">
    <h3>${thread.topic} [${thread.dateCreated}] <g:link controller="forumThread" action="show" id="${thread.id}">View</g:link></h3><br/>
    <g:each in="${thread.children.sort{it.dateCreated.getTime()}}" var="post">
        <g:render template="post" model="${[post: post]}"/>
    </g:each>
</div>

grails-app/views/forumBoard/create.gsp
<html>
<body>
    <g:form action="save">
        <g:render template="form" />
        <g:submitButton name="create" value="Create"/>
    </g:form>
</body>
</html>

grails-app/views/forumBoard/edit.gsp
<html>
<body>
    <g:form action="update" id="${board.id}">
        <g:render template="form" />
        <g:submitButton name="update" value="Update"/>
    </g:form>
</body>
</html>

grails-app/views/forumBoard/show.gsp
<html>
	<head>
		<meta name="layout" content="board">
		<title>${board.abbreviation}- ${board.name}</title>
	</head>
	<body>
	    <div class="title"><h1 class="board">${board.abbreviation}- ${board.name}</h1></div>
	    <hr />
	    <g:render template="/forumPost/newPostForm" model="${[controller: 'forumThread']}" />
	    <hr />
	    <g:each in="${threads}" var="thread">
	        <g:render template="/forumThread/threadPreview" model="${[thread: thread]}" />
	        <hr />
	    </g:each>
	    <g:paginate controller="forumBoard" action="board" id="${board.abbreviation.replaceAll('/', '')}" total="${threadCount}" />
	    <a href="${createLink(controller: 'forum', action: 'index')}">Return to index</a>
	</body>
</html>